### ISSUE TITLE
Expand & Collapse button

### ISSUE THREAD

**Issue by Saeed-Hassanpour** [RonnyWeiss/Apex-Fancy-Tree-Select#1]
Hi Ronny,
It seems the (Expand & Collapsed tree) Action are not working.

**Comment by RonnyWeiss** [comment]
Hello Saeed

I will take a look at the weekend. Do you mean apex dynamic tree expan and collapse?

**Comment by Saeed-Hassanpour** [comment]
Hi Ronny,
Yes exactly, it can be do that via dynamic action or Javascript API.

**Comment by RonnyWeiss** [comment]
Hello you can do this by setting expand state of tree items by apex items. So when apex items is 1 then all expanded when 0 then not. So feature is already available
