### ISSUE TITLE
Nodes not rendered properly when child has multiple parents

### ISSUE THREAD

**Issue by pcvdbroek** [RonnyWeiss/Apex-Fancy-Tree-Select#2]
The nodes are not properly rendered when a child is used on multiple parents (e.g. 1 type of screw is used in multiple sets or employee has more than 1 manager). Second occurrence of the child is rendered at the root with the wrong parentid

**Comment by RonnyWeiss** [comment]
So you need to unify that idents. in a tree leafs must be unqie. I will not support a multiple parent feature.
