### ISSUE TITLE
Selection Mode2

### ISSUE THREAD

**Issue by jeanmarc78** [RonnyWeiss/Apex-Fancy-Tree-Select#4]
Hello,
Would it possible when i manually check hierarchie 6 , that all the child nodes would be selected

![image](https://user-images.githubusercontent.com/11042160/107371127-2e7d8d80-6ae4-11eb-9a65-dba366ad5949.png)

the selection mode 2 is the most appropriate because would like to deselect a child like
![image](https://user-images.githubusercontent.com/11042160/107371443-946a1500-6ae4-11eb-82fa-16864621fcc5.png)

regards
jm

**Comment by RonnyWeiss** [comment]
I don't understand the problem. You can choose these 3 selection modes and your usecase should be covered. Or is there something missing?

**Comment by jeanmarc78** [comment]
i would like a mix with selection 2 and selection 3.

with selection 3 , when i select a parent, all child are selected, it 's good
![image](https://user-images.githubusercontent.com/11042160/107490624-68a16a80-6b8a-11eb-933c-5fadf99fdfef.png)

but when i deselect a child

![image](https://user-images.githubusercontent.com/11042160/107490887-c3d35d00-6b8a-11eb-9055-592e2341cf49.png)

the parent is deselected and i dont want this behavior , i would like
![image](https://user-images.githubusercontent.com/11042160/107491197-1ad93200-6b8b-11eb-98d8-2a23a66491ca.png)

**Comment by RonnyWeiss** [comment]
I Know what you mean but thats is not supported in Fanc tree and so this plugin cant handle that. Please use one of the three selection modes. 😀
