### ISSUE TITLE
not rtl suport

### ISSUE THREAD

**Issue by meysam-khashei** [RonnyWeiss/Apex-Fancy-Tree-Select#4]
Hi Ronny,
change this code
    ul.fancytree-container ul{padding:.3em 0 0 1em;margin:0}
to
    ul.fancytree-container ul{padding:.3em 1em 0 1em;margin:0}
in the file ancytree.pkgd.min.css for support right-to-left 
tanks.

**Comment by meysammkw** [comment]
hi
change this code
    ul.fancytree-container ul{padding:.3em 0 0 1em;margin:0}
to
    ul.fancytree-container ul{padding:.3em 1em 0 1em;margin:0}
in file ancytree.pkgd.min.css for suport right to left

**Comment by RonnyWeiss** [comment]
Just change it in theme. I will not support rtl mode. sorry
