### ISSUE TITLE
"Expand All" & "Collapse All" ??

### ISSUE THREAD

**Issue by Samraw003** [RonnyWeiss/Apex-Fancy-Tree-Select#5]
Hi,

Can you please share how to implement Collapse All and Expand All functionality?
Thanks

Sammeer

**Comment by RonnyWeiss** [comment]
Hi Sammeer

Thats quite easy you check my code in my sample app but Í will tell it to you:

You set a static ID to the fancy tree region:

![grafik](https://user-images.githubusercontent.com/30749177/121401409-fb93bb00-c958-11eb-9d99-dd143b1146c2.png)

then you create a dynamic action e.g. on a button click:

![grafik](https://user-images.githubusercontent.com/30749177/121401483-0fd7b800-c959-11eb-9765-9cba27958ae5.png)

and in JavaScript Block you set:

![grafik](https://user-images.githubusercontent.com/30749177/121401614-30a00d80-c959-11eb-98a0-7dcc896dffd7.png)


$("#tree1").trigger("expandAll");

and for collapse:

$("#tree1").trigger("collapseAll");

Hope that does help you 

Kind regards

Ronny

**Comment by Samraw003** [comment]
Hi Ronny,

Thanks a ton for the prompt reply and solution.

Regards

Sammeer
