### ISSUE TITLE
Open link in another tab

### ISSUE THREAD

**Issue by amdonato** [RonnyWeiss/Apex-Fancy-Tree-Select#6]
There's a way to set link to open in another tab? ("_blank")?

**Comment by RonnyWeiss** [comment]
Hello

Yes thats no problem just add this instead of a normal link:

javascript:window.open('https://linktr.ee/ronny.weiss', '_blank');void(0);

in your sql:

'javascript:window.open(''https://linktr.ee/ronny.weiss'', ''_blank'');void(0);'

Kind regards

Ronny
