### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by olezha5** [RonnyWeiss/Apex-Fancy-Tree-Select#8]
![20210927_133028](https://user-images.githubusercontent.com/20341634/134892491-faef3ca5-d871-4502-9da5-b66d35f1a3a0.jpg)

**Comment by RonnyWeiss** [comment]
Hello

Seems that your static files in APEX are generally not working. Can you please check that first?

Kind regards

Ronny

**Comment by olezha5** [comment]
Thanks, everything worked!
